### ISSUE TITLE
Why is offset not populated in interactive doc?

### ISSUE THREAD

**Issue by tschaffter** [Sage-Bionetworks/nlp-sandbox-data-node-i2b2-2014#67]
![image](https://user-images.githubusercontent.com/3056480/96328725-05983080-0ffb-11eb-9383-eebf94321975.png)

Here are the definition of offset and limit, which are almost identical:

```
  /notes:
    get:
      description: Returns the clinical notes
      operationId: notes_read_all
      parameters:
      - description: Maximum number of results returned
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: 10
          minimum: 10
          type: integer
        style: form
      - description: Index of the first result that must be returned
        explode: true
        in: query
        name: offset
        required: false
        schema:
          default: 0
          minimum: 0
          type: integer
        style: form
```

It does not seem to be a caching issue...
